### ISSUE TITLE
provide documentation

### ISSUE THREAD

**Issue by helmbold** [edda/cucumber-atom#5]
I don't see anything of this plug-in after installtion. I want to perform auto indentation, but don't see any menu point to do so.

Please provide a little bit more information how to use this plugin (even if you write that everything works automatically and can be configured in the settings).

**Comment by edda** [comment]
If you open the Atom settings you should see the Cucumber package settings among the other packages in the package listing. 

If by auto indentation you mean some sort of auto-formatting, the package doesn't have this I'm afraid. However you can have it auto indent the cursor when inserting a newline.
