### ISSUE TITLE
Create a Gherkin table parser.

### ISSUE THREAD

**Issue by carlosbaraza** [edda/cucumber-atom#8]
Create a snippet to order the table and set the align the different columns and rows.

This would be a very useful add-on to the package.

**Comment by siannopollo** [comment]
+1. This feature is available in the cucumber-tmbundle under the heading "Align Table Cells". Here is the [relevant code](https://github.com/cucumber/cucumber-tmbundle/blob/master/support/lib/cucumber/mate/table_aligner.rb) from the tmbundle.

**Comment by otoniel-isidoro** [comment]
+1

**Comment by kingbuzzman** [comment]
Whats the status of this?

**Comment by edda** [comment]
I am happy to accept pull requests adding this feature.

**Comment by edda** [comment]
This is included in version 0.6.0 thanks to @barthez
